# Generated by Django 5.2.14 on 2026-05-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeadRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('university', models.CharField(max_length=200, verbose_name='Университет')),
                ('role', models.CharField(choices=[('registrar', 'Регистратор / учебный офис'), ('dean', 'Декан / проректор'), ('it', 'ИТ / интеграции'), ('other', 'Другое')], default='other', max_length=32, verbose_name='Роль')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
            ],
            options={
                'verbose_name': 'Заявка с лендинга',
                'verbose_name_plural': 'Заявки с лендинга',
                'ordering': ['-created_at'],
            },
        ),
    ]
